# Generated by Django 3.0.7 on 2023-12-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20231213_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('ON', 'Ontario'), ('QC', 'Quebec'), ('BC', 'British Colombia'), ('AB', 'Alberta'), ('NS', 'Nova Scotia'), ('NB', 'New Brunswick'), ('MB', 'Manituba')], max_length=100),
        ),
    ]
